DROP TABLE ELECTION.CANDIDATE;
DROP TABLE ELECTION.VOTER;


CREATE TABLE ELECTION.CANDIDATE (
   CID CHAR(5) PRIMARY KEY,
   FIRST_NAME VARCHAR(20),
   LAST_NAME VARCHAR(20),
   CVOTES INTEGER DEFAULT 0
);

INSERT INTO ELECTION.CANDIDATE (CID, FIRST_NAME, LAST_NAME) VALUES ('C1000', 'Ju Wen', 'Chen');
INSERT INTO ELECTION.CANDIDATE (CID, FIRST_NAME, LAST_NAME) VALUES ('C2000', 'Grace', 'Semanio');
INSERT INTO ELECTION.CANDIDATE (CID, FIRST_NAME, LAST_NAME) VALUES ('C3000','Asif', 'Khan');

CREATE TABLE ELECTION.VOTER (
VPK INTEGER PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(12) NOT NULL,
VOTED BOOLEAN
) AUTO_INCREMENT = 301;


INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Abdul', 'Akmanizer', 'Alpha');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Bree', 'Beckham', 'Bravo');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Chaz','Cruz', 'Charlie');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Darshit', 'Desai', 'Delta');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Emily', 'Enbridge', 'Echo');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Fabio', 'Fremonte', 'Foxtrot');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('George', 'Griswald', 'Golf');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Harsh', 'Hedge', 'Hotel');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Iggie', 'Ianno', 'India');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('John', 'Ming','Juliet');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Kathleen', 'Kim', 'Kilo');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Leonard', 'Lassiter', 'Lima');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Meer', 'Metha', 'Mike');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Nadine', 'Ng', 'November');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Olga', 'Oleansky', 'Oscar');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Ping', 'Pan', 'Papa');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Quinton', 'Quirebrook', 'Quebec');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Rolanda', 'Romero', 'Romeo');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Sarah', 'Singh', 'Sierra');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Trever', 'Tillman', 'Tango');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Umberto', 'Unno', 'Uniform');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Vickor','Vessander', 'Victor');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('William', 'Winterbottom', 'Whiskey');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Xavier', 'Xu','X-ray');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Yang', 'Yuexiang', 'Yankee');
INSERT INTO ELECTION.VOTER(FIRST_NAME, LAST_NAME, PASSWORD ) VALUES ('Zippy', 'Zhou', 'Zulu');